version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    container_name: mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
      # - ./mosquitto/data:/mosquitto/data # OPTIONAL: uncomment if you want MQTT broker host Persistence
    user: "${USER_ID}:${GRP_ID}"
    ports:
      - "1883:1883"
    links:
      - telegraf
    restart: always
    networks:
      - "iotstack"
  
  telegraf:
    image: telegraf
    container_name: telegraf
    env_file: questitto.env
    volumes:
      - ./telegraf/telegraf.toml:/etc/telegraf/telegraf.conf:ro
    networks:
      - "iotstack"

networks:
  iotstack:
    external: true